name: Ejecutar analizar.py diariamente

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  ejecutar-analizar:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v4

      - name: Mostrar estructura del proyecto
        run: ls -R

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install pandas scikit-learn joblib

      - name: Ejecutar script
        run: |
          echo "Ejecutando analizar.py..."
          python analizar.py --predecir
